#!/usr/bin/env node
// Build Minecraft releases and publish the archives as GitHub Releases.
//
//   node tools/publish.mjs --repo owner/name              # latest release, if not published
//   node tools/publish.mjs --repo owner/name --all        # every mirror release not published
//   node tools/publish.mjs --repo owner/name --version 26.3
//   node tools/publish.mjs --repo owner/name --dry-run
//
// Requires the GitHub CLI (`gh`), authenticated via GH_TOKEN/GITHUB_TOKEN.

import { stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { buildAssets } from "./build-assets.mjs";
import { buildSounds } from "./build-sounds.mjs";
import {
  listMirrorBranches,
  listOfficialVersions,
  latestOfficialVersion,
  isReleaseVersion,
  cmpVersion,
  CHANNELS,
} from "./lib/repo.mjs";

const run = promisify(execFile);

function parseArgs(argv) {
  const out = {
    out: "out",
    repo: process.env.GITHUB_REPOSITORY || null,
    source: "mojang",
    channel: "release",
    version: null,
    all: false,
    from: null,
    assets: true,
    sounds: true,
    dryRun: false,
    tagPrefix: "",
    forward: [],
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = () => argv[++i];
    if (a === "--out") out.out = next();
    else if (a === "--repo") out.repo = next();
    else if (a === "--source") out.source = next();
    else if (a === "--channel") out.channel = next();
    else if (a === "--version") out.version = next();
    else if (a === "--all") out.all = true;
    else if (a === "--from") out.from = next();
    else if (a === "--no-assets") out.assets = false;
    else if (a === "--no-sounds") out.sounds = false;
    else if (a === "--dry-run") out.dryRun = true;
    else if (a === "--tag-prefix") out.tagPrefix = next();
    else if (["--size", "--thumb", "--limit", "--concurrency"].includes(a)) out.forward.push(a, next());
    else if (a === "--help" || a === "-h") {
      console.log(`usage: node tools/publish.mjs --repo <owner/name> [options]
  --repo <owner/name>  target repository (default: $GITHUB_REPOSITORY)
  --out <dir>          build/output root (default: out)
  --source <src>       choose the "latest" from mojang (official) or mirror (default: mojang)
  --channel <ch>       release | snapshot | both (default: release)
  --version <v>        publish this version regardless of the missing check
  --all                publish every mirror release not yet published
  --from <version>     with --all, only releases newer than this version
  --no-assets          skip icons/textures
  --no-sounds          skip sounds
  --dry-run            list what would be published without building
  --tag-prefix <p>     release tag prefix (default: none, e.g. "mc-" -> mc-26.3)
  --size/--thumb/--limit/--concurrency  forwarded to the builders`);
      process.exit(0);
    }
  }
  if (!["mojang", "mirror"].includes(out.source)) throw new Error(`unknown --source "${out.source}"`);
  if (!CHANNELS.includes(out.channel)) throw new Error(`unknown --channel "${out.channel}" (use ${CHANNELS.join(", ")})`);
  return out;
}

const isFile = async (p) => {
  try {
    return (await stat(p)).isFile();
  } catch {
    return false;
  }
};

async function gh(args) {
  try {
    const { stdout } = await run("gh", args, { maxBuffer: 256 * 1024 * 1024 });
    return stdout;
  } catch (err) {
    throw new Error(`gh ${args.slice(0, 3).join(" ")} failed: ${err.stderr?.trim() || err.message}`);
  }
}

async function ensureGh() {
  try {
    await run("gh", ["--version"]);
  } catch {
    throw new Error("the GitHub CLI (gh) is required to publish releases");
  }
}

async function publishedTags(repo) {
  const text = await gh([
    "release",
    "list",
    "--repo",
    repo,
    "--limit",
    "1000",
    "--json",
    "tagName",
    "--jq",
    ".[].tagName",
  ]);
  return new Set(text.split("\n").map((s) => s.trim()).filter(Boolean));
}

const releaseNotes = (version, files) =>
  `Minecraft ${version} asset library, generated by devault from the ` +
  `InventivetalentDev/minecraft-assets mirror.\n\n` +
  files.map((f) => `- \`${path.basename(f)}\``).join("\n") +
  `\n\nGenerated ${new Date().toISOString()}.\n` +
  `Minecraft assets belong to Mojang/Microsoft; devault is an unaffiliated index over them.`;

async function buildArchives(args, out, version) {
  const files = [];
  if (args.assets) {
    await buildAssets(["--out", out, "--version", version, ...args.forward]);
    const zip = path.join(out, `${version}.zip`);
    if (await isFile(zip)) files.push(zip);
  }
  if (args.sounds) {
    await buildSounds(["--out", out, "--version", version, "--zip", ...args.forward]);
    const zip = path.join(out, `${version}-sounds.zip`);
    if (await isFile(zip)) files.push(zip);
  }
  return files;
}

export async function publishReleases(argv = process.argv.slice(2)) {
  const args = parseArgs(argv);
  if (!args.repo) throw new Error("no repo; pass --repo owner/name or set GITHUB_REPOSITORY");
  const out = path.resolve(args.out);

  const mirror = new Set(await listMirrorBranches());
  const official = await listOfficialVersions(args.channel); // newest first
  const buildable = official.map((v) => v.id).filter((id) => mirror.has(id)); // newest first
  const published = await publishedTags(args.repo);

  let targets;
  if (args.version) {
    if (!mirror.has(args.version)) throw new Error(`${args.version} is not on the mirror`);
    targets = [args.version];
  } else if (args.all || args.from) {
    targets = buildable.slice().reverse(); // oldest first
    if (args.from) {
      const i = targets.indexOf(args.from);
      targets = i >= 0 ? targets.slice(i + 1) : targets.filter((v) => cmpVersion(v, args.from) > 0);
    }
  } else {
    const latest = args.source === "mirror" ? buildable[0] : await latestOfficialVersion(args.channel);
    if (!latest) {
      console.log("no known versions for this channel — nothing to do");
      return;
    }
    if (!mirror.has(latest)) {
      console.log(`latest ${args.source} ${args.channel} version ${latest} is not on the mirror yet — nothing to do`);
      return;
    }
    targets = [latest];
  }

  targets = targets.filter((v) => !published.has(args.tagPrefix + v));
  if (!targets.length) {
    console.log("nothing to publish — every candidate already has a release");
    return;
  }
  console.log(`to publish (${targets.length}): ${targets.join(", ")}`);
  if (args.dryRun) {
    for (const v of targets) {
      console.log(`  ${args.tagPrefix}${v}  (assets:${args.assets}, sounds:${args.sounds})`);
    }
    return;
  }

  await ensureGh();
  const newestRelease = [...targets].reverse().find(isReleaseVersion);
  for (const version of targets) {
    const files = await buildArchives(args, out, version);
    if (!files.length) {
      console.warn(`  ${version}: no archives produced, skipping release`);
      continue;
    }
    const tag = `${args.tagPrefix}${version}`;
    const ghArgs = [
      "release",
      "create",
      tag,
      ...files,
      "--repo",
      args.repo,
      "--title",
      `Minecraft ${version}`,
      "--notes",
      releaseNotes(version, files),
    ];
    if (isReleaseVersion(version)) ghArgs.push(version === newestRelease ? "--latest" : "--latest=false");
    else ghArgs.push("--prerelease", "--latest=false");
    console.log(`  creating release ${tag} (${files.length} file(s))…`);
    await gh(ghArgs);
    console.log(`  published ${tag}`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  publishReleases().catch((err) => {
    console.error(`devault publish: ${err.message}`);
    process.exit(1);
  });
}
